# Matches Open OnDemand style guidelines
# https://github.com/OSC/ondemand/blob/master/.rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'mcp/**/*'

# HTTP status codes in test names are meaningful (401, 503, etc.)
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

# These methods appropriately return booleans without needing ? suffix
Naming/PredicateMethod:
  AllowedMethods:
    - destroy
    - touch_last_used!

# style
Style/MultilineBlockChain:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: 'no_mixed_keys'
Style/ClassAndModuleChildren:
  EnforcedStyle: 'nested'
Style/WordArray:
  EnforcedStyle: 'brackets'
Style/SymbolArray:
  EnforcedStyle: 'brackets'
Style/Documentation:
  Enabled: false

# layout
Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 120

# metrics
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - 'heredoc'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
